# Minimal, fast debug run on CPU
train:
  seed: 0
  validate_at_start: true
  test: false
  ckpt: null
  ckpt_dir: ~/ckpt

dataset:
  name: trajectory_generation
  bsz: 8
  num_workers: 0
  data_dir: ~/data/traj/basketball
  input_type: raw
  target_type: raw
  traj_space_width: 94
  traj_space_height: 50
  pad_start_of_sequence: false

# Small model for speed (used by CPU class after the code tweak below)
model:
  name: transformer
  args:
    context_length: 49
    n_layer: 4
    d_model: 64
    n_head: 4
    d_ff: 256
    use_rope: True
    theta: 10000.0
    input_type: raw
    output_type: values
    out_value_size: 22
    n_encoder_layer: 2
    input_value_size: 22

metrics: ["loss", "ade"]

# Optimizer
lr: 0.001
weight_decay: 0.01
lr_schedule: false
pct_start: 0.1
total_steps: null
task_type: generation
loss: mse
output2input_preprocess_fn_name: null

# Lightning Trainer
trainer:
  accelerator: cpu
  devices: 1
  precision: bf16-true
  max_epochs: 1
  fast_dev_run: true           # one batch train/val/test and exit
  limit_train_batches: 2       # safety; only a couple batches
  limit_val_batches: 1
  limit_test_batches: 0
  log_every_n_steps: 1
  enable_checkpointing: false

wandb:
  project: transformer-traj
  name: dryrun
callbacks:
  TrajectoryPrefixSamplerCallback:
    num_samples: 3
    every_n_epochs: 1
    sample_prefix_length: 10
    max_length: 50
    downsampling_ratio: 5
    fps: 2
    game: basketball
    sample_dir: ~/samples/transformer-traj-dryrun