# Training run config
train:
  seed: 42
  validate_at_start: true
  test: true
  ckpt: null
  ckpt_dir: ~/ckpt/mamba2-xkparams-schedule2

dataset:
  name: mnist_generation
  bsz: 128
  num_workers: 0
  data_dir: ~/data
  input_type: raw
  target_type: token

# Small model for speed (used by CPU class after the code tweak below)
model:
  name: mamba2_fused
  args:
    n_layer: 3
    d_model: 128
    d_intermediate: 0
    vocab_size: 256
    ssm_cfg:
      layer: Mamba2
      d_state: 64
      d_conv: 4
      expand: 2
      headdim: 16
      ngroups: 1
      chunk_size: 128
      bias: false
      conv_bias: false
    rms_norm: true
    fused_add_norm: true
    residual_in_fp32: true
    input_type: raw
    output_type: logits

metrics: ["loss", "accuracy"]

# Optimizer
lr: 0.003
weight_decay: 0.0
lr_schedule: true
pct_start: 0.1
div_factor: 15.0
final_div_factor: 500.0

total_steps: null
task_type: generation
loss: cross_entropy
output2input_preprocess_fn_name: mnist_token2raw

# Lightning Trainer
trainer:
  accelerator: gpu
  devices: 1
  precision: 32
  max_epochs: 100
  fast_dev_run: false          # one batch train/val/test and exit
  limit_train_batches: null       # safety; only a couple batches
  limit_val_batches: null
  limit_test_batches: null
  log_every_n_steps: null
  enable_checkpointing: true

wandb:
  project: mamba2-mnist
  name: xkparams-schedule-nowd-lr3e-3
callbacks:
  ImagePrefixSamplerCallback:
    num_samples: 8
    every_n_epochs: 1
    sample_prefix_length: 257
    max_length: 785