# Minimal, fast debug run on CPU
train:
  seed: 0
  validate_at_start: true
  test: false
  ckpt: null

dataset:
  name: mnist_generation
  bsz: 8
  num_workers: 0
  data_dir: ~/projects/data
  input_type: raw
  target_type: token

# Small model for speed (used by CPU class after the code tweak below)
model:
  name: s4
  args:
    d_input: 1
    vocab_size: 256
    d_model: 128
    n_layers: 4
    dropout: 0.2
    d_state: 128
    prenorm: true
    lr: 0.0001
    wd: 0.0
    input_type: raw
    output_type: logits
    backend: naive

metrics: ["loss"]

# Optimizer
lr: 0.001
weight_decay: 0.01
lr_schedule: false
pct_start: 0.1
total_steps: null
task_type: generation
loss: cross_entropy
output2input_preprocess_fn_name: mnist_token2raw

# Lightning Trainer
trainer:
  accelerator: cpu
  devices: 1
  precision: 32
  max_epochs: 1
  fast_dev_run: true           # one batch train/val/test and exit
  limit_train_batches: 2       # safety; only a couple batches
  limit_val_batches: 1
  limit_test_batches: 0
  log_every_n_steps: 1
  enable_checkpointing: false

wandb:
  project: s4-mnist
  name: dryrun
callbacks: 
  ImagePrefixSamplerCallback:
    num_samples: 8
    every_n_epochs: 1
    sample_prefix_length: 257
    max_length: 785