# Training run config
train:
  seed: 42
  validate_at_start: true
  test: true
  ckpt: null
  ckpt_dir: ~/ckpt

dataset:
  name: trajectory_generation
  bsz: 128
  num_workers: 0
  data_dir: ~/data/traj/basketball
  input_type: raw
  target_type: raw
  traj_space_width: 94
  traj_space_height: 50
  pad_start_of_sequence: false

model:
  name: mamba2_fused
  args:
    n_layer: 8
    d_model: 64
    d_intermediate: 0
    attn_layer_idx: [2,5]
    attn_cfg:
      num_heads: 4
      mlp_dim: 0
      qkv_proj_bias: false
      out_proj_bias: false
      softmax_scale: null
      causal: true
      d_conv: 0
      rotary_emb_dim: 16
      rotary_emb_base: 10000.0
      rotary_emb_interleaved: true
    ssm_cfg:
      layer: Mamba2
      d_state: 128
      d_conv: 4
      expand: 2
      headdim: 16
      ngroups: 1
      chunk_size: 128
    rms_norm: true
    fused_add_norm: true
    residual_in_fp32: false
    input_type: raw
    output_type: values
    out_value_size: 22
    n_encoder_layer: 2
    input_value_size: 22

metrics:
  loss: null
  ade: # if idxs given, additionally log stratified metric for each group
    prefix_length: 30
    grouping:
      ball: [0]
      player_team_a: [1, 2, 3, 4, 5]
      player_team_b: [6, 7, 8, 9, 10]

# Optimizer
lr: 0.0003
weight_decay: 0.01
lr_schedule: true
pct_start: 0.1
div_factor: 15.0
final_div_factor: 500.0
beta1: 0.9
beta2: 0.95
total_steps: null
task_type: generation
loss: mse
output2input_preprocess_fn_name: null

# Lightning Trainer
trainer:
  accelerator: gpu
  devices: 1
  precision: "bf16-true"
  max_epochs: 100
  fast_dev_run: false          # one batch train/val/test and exit
  limit_train_batches: null       # safety; only a couple batches
  limit_val_batches: null
  limit_test_batches: null
  log_every_n_steps: null
  enable_checkpointing: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm

wandb:
  project: mamba2attn-traj
  name: xkparams-schedule-lr3e-3
callbacks:
  TrajectoryPrefixSamplerCallback:
    num_samples: 4
    every_n_epochs: 5
    sample_prefix_length: 25
    max_length: 50
    downsampling_ratio: 1
    fps: 5
    game: basketball
    sample_dir: ~/samples